server:
  port: 80
  servlet:
    context-path: /sube-svc/api

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  health:
    redis:
      enable: false

spring:
  profiles:
    active: dev
  application:
    name: sube-svc
  data:
    mongodb:
      uri: ${MONGODB_URI_SUBE:mongodb+srv://contactolbernal:AWk1QZE68VfZs8f0@subetest.uvc6f.mongodb.net/subedb}
#  mail:
#    host: ${EMAIL_HOST:smtp.gmail.com}
#    port: ${EMAIL_PORT:587}
#    username: ${EMAIL_SEND:tu_correo@gmail.com}
#    password: ${EMAIL_PASSWORD:tu_contraseña}
#    protocol: smtp
#    tls: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true